/*
 * Minimal stub of the Opcode OMSGlueProcs.h call-number surface used by
 * the USBMIDI9 OMS shim (oms/oms_driver.c resolves the 68K
 * OMSReceivedFromPort address via OMSGetCallAddress). NOT the real
 * header — see OMS.h in this directory for the policy.
 *
 * The authentic file is GENERATED by Opcode ("*** THIS FILE GENERATED
 * AUTOMATICALLY -- DO NOT MODIFY ***", OMS 2.0 SDK 28-Jan-98
 * Headers/OMSGlueProcs.h); only the constant the shim needs is modeled.
 * The G4 build uses the authentic header from OMS SDK:Headers:.
 */

#ifndef USBMIDI9_HOST_CHECK_OMSGLUEPROCS_H
#define USBMIDI9_HOST_CHECK_OMSGLUEPROCS_H

/* OMSGlueProcs.h (authentic, generated): call number of the 68K
 * OMSReceivedFromPort assembly routine (OMSDriver.h declares it only
 * for !powerc; the Spec directs PPC code to obtain its address with
 * OMSGetCallAddress(callOMSReceivedFromPort)). */
#define callOMSReceivedFromPort 112

#endif /* USBMIDI9_HOST_CHECK_OMSGLUEPROCS_H */
